name: Stock Checker

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run the stock checker
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python checker.py
          
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update notified URLs list
          file_pattern: notified_urls.txt

      # --- RE-ADD THIS STEP TO UPLOAD OUR EVIDENCE ---
      - name: Upload Diagnostic Artifacts
        if: always() # This makes it run even if previous steps fail
        uses: actions/upload-artifact@v4
        with:
          name: diagnostic-files
          path: |
            *.html
            *.png
      # ---------------------------------------------
