name: Stock Checker

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run the diagnostic script
        run: python checker.py
          
      - name: Upload Diagnostic Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: diagnostic-files
          path: |
            *.html
            *.png
